name: Docker push
on:
  repository_dispatch:
    types: [docker_push]
jobs:
  docker_push:
    name: Docker push
    runs-on: ubuntu-18.04
    needs: [docker_build]
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Set environment variables from scripts
      run: |
        . bin/_tag.sh
        echo ::set-env name=TAG::$(CI_FORCE_CLEAN=1 bin/root-tag)
    - name: Configure gcloud
      # linkerd/linkerd2-action-gcloud@v1.0.1
      uses: linkerd/linkerd2-action-gcloud@308c4df
      with:
        cloud_sdk_service_account_key: ${{ secrets.CLOUD_SDK_SERVICE_ACCOUNT_KEY }}
        gcp_project: ${{ secrets.GCP_PROJECT }}
        gcp_zone: ${{ secrets.GCP_ZONE }}
    - name: Docker SSH setup
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/id && chmod 600 ~/.ssh/id
        echo "${{ secrets.DOCKER_SSH_CONFIG }}"  > ~/.ssh/config
        echo "${{ secrets.DOCKER_PRIVATE_KEY }}" > ~/.ssh/id
        echo "${{ secrets.DOCKER_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        ssh linkerd-docker docker version
    - name: Push docker images to registry
      env:
        DOCKER_HOST: ssh://linkerd-docker
      run: |
        export PATH="`pwd`/bin:$PATH"
        bin/docker-push-deps
        bin/docker-push $TAG
        bin/docker-retag-all $TAG master
        bin/docker-push master
    - name: Start cloud integration tests
      if: ${{ github.event.client_payload.release }} == 'false'
      # peter-evans/repository-dispatch@v1
      uses: peter-evans/repository-dispatch@0ae1c4b
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        repository: linkerd/linkerd2
        event-type: cloud-integration-tests
    - name: Start release
      if: ${{ github.event.client_payload.release }} == 'true'
      # peter-evans/repository-dispatch@v1
      uses: peter-evans/repository-dispatch@0ae1c4b
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        repository: linkerd/linkerd2
        event-type: release
